Repository zbrateam/Zebra, pull requests merged in 2019-12, with the labels that each got.

#639 [Localization] 1.0~beta31 translations
  Zebra/ar.lproj/Localizable.strings
  Zebra/cs.lproj/Localizable.strings
  Zebra/da.lproj/Localizable.strings
  Zebra/de.lproj/Localizable.strings
  Zebra/el.lproj/Localizable.strings
  Zebra/es.lproj/Localizable.strings
  Zebra/fa.lproj/Localizable.strings
  Zebra/fr.lproj/Localizable.strings
  Zebra/he.lproj/Localizable.strings
  Zebra/hi.lproj/Localizable.strings
  Zebra/hr.lproj/Localizable.strings
  Zebra/id.lproj/Localizable.strings
  Zebra/it.lproj/Localizable.strings
  Zebra/ja.lproj/Localizable.strings
  Zebra/ko.lproj/Localizable.strings
  Zebra/lt.lproj/Localizable.strings
  Zebra/lv.lproj/Localizable.strings
  Zebra/nb.lproj/Localizable.strings
  Zebra/nl.lproj/Localizable.strings
  Zebra/nn.lproj/Localizable.strings
  Zebra/pl.lproj/Localizable.strings
  Zebra/pt-BR.lproj/Localizable.strings
  Zebra/pt.lproj/Localizable.strings
  Zebra/ru.lproj/Localizable.strings
  Zebra/sk.lproj/Localizable.strings
  Zebra/sq.lproj/Localizable.strings
  Zebra/sr.lproj/Localizable.strings
  Zebra/sv.lproj/Localizable.strings
  Zebra/th.lproj/Localizable.strings
  Zebra/tr.lproj/Localizable.strings
  Zebra/vi.lproj/Localizable.strings
  Zebra/zh-Hans.lproj/Localizable.strings
  Zebra/zh-Hant.lproj/Localizable.strings
Labels: localization, scheduled

#669 Update ZBAlternateIconController.m
  Zebra/Tabs/Home/Alternate Icons/ZBAlternateIconController.m
Labels: enhancement

#661 [Localization] 1.0~beta32 translations
  Zebra/ar.lproj/Localizable.strings
  Zebra/cs.lproj/Localizable.strings
  Zebra/da.lproj/Localizable.strings
  Zebra/de.lproj/Localizable.strings
  Zebra/el.lproj/Localizable.strings
  Zebra/es.lproj/Localizable.strings
  Zebra/fa.lproj/Localizable.strings
  Zebra/fr.lproj/Localizable.strings
  Zebra/he.lproj/Localizable.strings
  Zebra/hi.lproj/Localizable.strings
  Zebra/hr.lproj/Localizable.strings
  Zebra/hu.lproj/Localizable.strings
  Zebra/id.lproj/Localizable.strings
  Zebra/it.lproj/Localizable.strings
  Zebra/ja.lproj/Localizable.strings
  Zebra/ko.lproj/Localizable.strings
  Zebra/lt.lproj/Localizable.strings
  Zebra/lv.lproj/Localizable.strings
  Zebra/nb.lproj/Localizable.strings
  Zebra/nl.lproj/Localizable.strings
  Zebra/nn.lproj/Localizable.strings
  Zebra/pl.lproj/Localizable.strings
  Zebra/pt-BR.lproj/Localizable.strings
  Zebra/pt.lproj/Localizable.strings
  Zebra/ru.lproj/Localizable.strings
  Zebra/sk.lproj/Localizable.strings
  Zebra/sq.lproj/Localizable.strings
  Zebra/sr.lproj/Localizable.strings
  Zebra/sv.lproj/Localizable.strings
  Zebra/th.lproj/Localizable.strings
  Zebra/tr.lproj/Localizable.strings
  Zebra/vi.lproj/Localizable.strings
  Zebra/zh-Hans.lproj/Localizable.strings
  Zebra/zh-Hant.lproj/Localizable.strings
Labels: localization, scheduled

#684 [Localization] New Translations
  Zebra/ar.lproj/Localizable.strings
  Zebra/cs.lproj/Localizable.strings
  Zebra/da.lproj/Localizable.strings
  Zebra/de.lproj/Localizable.strings
  Zebra/el.lproj/Localizable.strings
  Zebra/es.lproj/Localizable.strings
  Zebra/fa.lproj/Localizable.strings
  Zebra/fr.lproj/Localizable.strings
  Zebra/he.lproj/Localizable.strings
  Zebra/hi.lproj/Localizable.strings
  Zebra/hr.lproj/Localizable.strings
  Zebra/hu.lproj/Localizable.strings
  Zebra/id.lproj/Localizable.strings
  Zebra/it.lproj/Localizable.strings
  Zebra/ja.lproj/Localizable.strings
  Zebra/ko.lproj/Localizable.strings
  Zebra/lt.lproj/Localizable.strings
  Zebra/lv.lproj/Localizable.strings
  Zebra/nb.lproj/Localizable.strings
  Zebra/nl.lproj/Localizable.strings
  Zebra/nn.lproj/Localizable.strings
  Zebra/pl.lproj/Localizable.strings
  Zebra/pt-BR.lproj/Localizable.strings
  Zebra/pt.lproj/Localizable.strings
  Zebra/ru.lproj/Localizable.strings
  Zebra/sk.lproj/Localizable.strings
  Zebra/sq.lproj/Localizable.strings
  Zebra/sr.lproj/Localizable.strings
  Zebra/sv.lproj/Localizable.strings
  Zebra/th.lproj/Localizable.strings
  Zebra/tr.lproj/Localizable.strings
  Zebra/vi.lproj/Localizable.strings
  Zebra/zh-Hans.lproj/Localizable.strings
  Zebra/zh-Hant.lproj/Localizable.strings
Labels: localization, scheduled

#692 [Localization] New Translations
  Zebra/cs.lproj/Localizable.strings
  Zebra/da.lproj/Localizable.strings
  Zebra/de.lproj/Localizable.strings
  Zebra/es.lproj/Localizable.strings
  Zebra/hi.lproj/Localizable.strings
  Zebra/hr.lproj/Localizable.strings
  Zebra/it.lproj/Localizable.strings
  Zebra/ja.lproj/Localizable.strings
  Zebra/ko.lproj/Localizable.strings
  Zebra/lt.lproj/Localizable.strings
  Zebra/lv.lproj/Localizable.strings
  Zebra/nl.lproj/Localizable.strings
  Zebra/ru.lproj/Localizable.strings
  Zebra/sk.lproj/Localizable.strings
  Zebra/tr.lproj/Localizable.strings
Labels: localization, scheduled

#703 [Localization] New Translations
  Zebra/ar.lproj/Localizable.strings
  Zebra/cs.lproj/Localizable.strings
  Zebra/da.lproj/Localizable.strings
  Zebra/de.lproj/Localizable.strings
  Zebra/el.lproj/Localizable.strings
  Zebra/es.lproj/Localizable.strings
  Zebra/fa.lproj/Localizable.strings
  Zebra/fr.lproj/Localizable.strings
  Zebra/he.lproj/Localizable.strings
  Zebra/hi.lproj/Localizable.strings
  Zebra/hr.lproj/Localizable.strings
  Zebra/hu.lproj/Localizable.strings
  Zebra/id.lproj/Localizable.strings
  Zebra/it.lproj/Localizable.strings
  Zebra/ja.lproj/Localizable.strings
  Zebra/ko.lproj/Localizable.strings
  Zebra/lt.lproj/Localizable.strings
  Zebra/lv.lproj/Localizable.strings
  Zebra/nb.lproj/Localizable.strings
  Zebra/nl.lproj/Localizable.strings
  Zebra/nn.lproj/Localizable.strings
  Zebra/pl.lproj/Localizable.strings
  Zebra/pt-BR.lproj/Localizable.strings
  Zebra/pt.lproj/Localizable.strings
  Zebra/ru.lproj/Localizable.strings
  Zebra/sk.lproj/Localizable.strings
  Zebra/sq.lproj/Localizable.strings
  Zebra/sr.lproj/Localizable.strings
  Zebra/sv.lproj/Localizable.strings
  Zebra/th.lproj/Localizable.strings
  Zebra/tr.lproj/Localizable.strings
  Zebra/vi.lproj/Localizable.strings
  Zebra/zh-Hans.lproj/Localizable.strings
  Zebra/zh-Hant.lproj/Localizable.strings
Labels: localization, scheduled

#713 [Localization] New Translations
  Zebra/da.lproj/Localizable.strings
  Zebra/de.lproj/Localizable.strings
  Zebra/fr.lproj/Localizable.strings
  Zebra/id.lproj/Localizable.strings
  Zebra/it.lproj/Localizable.strings
  Zebra/sq.lproj/Localizable.strings
  Zebra/sr.lproj/Localizable.strings
  Zebra/th.lproj/Localizable.strings
  Zebra/tr.lproj/Localizable.strings
Labels: localization, scheduled

#751 [Localization] New Translations
  Zebra/cs.lproj/Localizable.strings
  Zebra/de.lproj/Localizable.strings
  Zebra/he.lproj/Localizable.strings
  Zebra/sk.lproj/Localizable.strings
  Zebra/tr.lproj/Localizable.strings
  Zebra/vi.lproj/Localizable.strings
  Zebra/zh-Hant.lproj/Localizable.strings
Labels: localization, scheduled

#756 [Localization] Update Chinese (Traditional) translations
  Zebra/zh-Hant.lproj/Localizable.strings
Labels: localization
