Repository zbrateam/Zebra, pull requests merged in 2019-11, with the labels that each got.

#494 [Localization] 1.0~beta24 Translations
  Zebra.xcodeproj/project.pbxproj
  Zebra/ar.lproj/Localizable.strings
  Zebra/cs.lproj/Localizable.strings
  Zebra/da.lproj/Localizable.strings
  Zebra/de.lproj/Localizable.strings
  Zebra/el.lproj/Localizable.strings
  Zebra/es.lproj/Localizable.strings
  Zebra/fr.lproj/Localizable.strings
  Zebra/he.lproj/Localizable.strings
  Zebra/hr.lproj/Localizable.strings
  Zebra/it.lproj/Localizable.strings
  Zebra/ja.lproj/Localizable.strings
  Zebra/ko.lproj/Localizable.strings
  Zebra/lt.lproj/Localizable.strings
  Zebra/lv.lproj/Localizable.strings
  Zebra/nb.lproj/Localizable.strings
  Zebra/nl.lproj/Localizable.strings
  Zebra/nn.lproj/Localizable.strings
  Zebra/pl.lproj/Localizable.strings
  Zebra/pt-BR.lproj/Localizable.strings
  Zebra/pt.lproj/Localizable.strings
  Zebra/ru.lproj/Localizable.strings
  Zebra/sk.lproj/Localizable.strings
  Zebra/sr.lproj/Localizable.strings
  Zebra/sv.lproj/Localizable.strings
  Zebra/th.lproj/Localizable.strings
  Zebra/tr.lproj/Localizable.strings
  Zebra/vi.lproj/Localizable.strings
  Zebra/zh-Hans.lproj/Localizable.strings
  Zebra/zh-Hant-HK.lproj/Localizable.strings
  Zebra/zh-Hant.lproj/Localizable.strings
Labels: localization, scheduled

#508 [Packages] Sorting using date now shows the exact dates
  Zebra.xcodeproj/project.pbxproj
  Zebra/Tabs/Changes/ZBChangesTableViewController.m
  Zebra/Tabs/Packages/Controllers/ZBPackageListTableViewController.m
  Zebra/Tabs/Packages/Helpers/ZBPackage.m
  Zebra/Tabs/Packages/Helpers/ZBPackagePartitioner.h
  Zebra/Tabs/Packages/Helpers/ZBPackagePartitioner.m
  Zebra/Tabs/Packages/Helpers/ZBSortingType.h
Labels: enhancement

#513 Update settings page to better support localizations
  Zebra.xcodeproj/project.pbxproj
  Zebra/Tabs/Home/Helpers/ZBWebViewController.m
  Zebra/Tabs/Home/Settings/Graphics/ZBSettingsOptionsTableViewController.h
  Zebra/Tabs/Home/Settings/Graphics/ZBSettingsOptionsTableViewController.m
  Zebra/Tabs/Home/Settings/ZBSettingsTableViewController.m
  Zebra/Tabs/Home/ZBHomeTableViewController.m
Labels: enhancement, localization

#504 [Localization] 1.0~beta25 translations
  Zebra/ar.lproj/Localizable.strings
  Zebra/cs.lproj/Localizable.strings
  Zebra/da.lproj/Localizable.strings
  Zebra/de.lproj/Localizable.strings
  Zebra/el.lproj/Localizable.strings
  Zebra/es.lproj/Localizable.strings
  Zebra/fr.lproj/Localizable.strings
  Zebra/he.lproj/Localizable.strings
  Zebra/hi.lproj/Localizable.strings
  Zebra/hr.lproj/Localizable.strings
  Zebra/it.lproj/Localizable.strings
  Zebra/ja.lproj/Localizable.strings
  Zebra/ko.lproj/Localizable.strings
  Zebra/lt.lproj/Localizable.strings
  Zebra/lv.lproj/Localizable.strings
  Zebra/nb.lproj/Localizable.strings
  Zebra/nl.lproj/Localizable.strings
  Zebra/nn.lproj/Localizable.strings
  Zebra/pl.lproj/Localizable.strings
  Zebra/pt-BR.lproj/Localizable.strings
  Zebra/pt.lproj/Localizable.strings
  Zebra/ru.lproj/Localizable.strings
  Zebra/sk.lproj/Localizable.strings
  Zebra/sr.lproj/Localizable.strings
  Zebra/sv.lproj/Localizable.strings
  Zebra/th.lproj/Localizable.strings
  Zebra/tr.lproj/Localizable.strings
  Zebra/vi.lproj/Localizable.strings
  Zebra/zh-Hans.lproj/Localizable.strings
  Zebra/zh-Hant.lproj/Localizable.strings
Labels: localization, scheduled

#530 [Localization] 1.0~beta26 translations
  Zebra/ar.lproj/Localizable.strings
  Zebra/cs.lproj/Localizable.strings
  Zebra/da.lproj/Localizable.strings
  Zebra/de.lproj/Localizable.strings
  Zebra/el.lproj/Localizable.strings
  Zebra/es.lproj/Localizable.strings
  Zebra/fr.lproj/Localizable.strings
  Zebra/he.lproj/Localizable.strings
  Zebra/hi.lproj/Localizable.strings
  Zebra/hr.lproj/Localizable.strings
  Zebra/it.lproj/Localizable.strings
  Zebra/ja.lproj/Localizable.strings
  Zebra/ko.lproj/Localizable.strings
  Zebra/lt.lproj/Localizable.strings
  Zebra/lv.lproj/Localizable.strings
  Zebra/nb.lproj/Localizable.strings
  Zebra/nl.lproj/Localizable.strings
  Zebra/nn.lproj/Localizable.strings
  Zebra/pl.lproj/Localizable.strings
  Zebra/pt-BR.lproj/Localizable.strings
  Zebra/pt.lproj/Localizable.strings
  Zebra/ru.lproj/Localizable.strings
  Zebra/sk.lproj/Localizable.strings
  Zebra/sr.lproj/Localizable.strings
  Zebra/sv.lproj/Localizable.strings
  Zebra/th.lproj/Localizable.strings
  Zebra/tr.lproj/Localizable.strings
  Zebra/vi.lproj/Localizable.strings
  Zebra/zh-Hans.lproj/Localizable.strings
  Zebra/zh-Hant.lproj/Localizable.strings
Labels: localization, scheduled

#545 Improved german translation
  Zebra/de.lproj/Localizable.strings
Labels: localization

#559 [Localization] Add Persian translations
  Zebra/fa.lproj/Localizable.strings
Labels: localization

#540 [Localization] 1.0~beta27 translations
  Zebra/ar.lproj/Localizable.strings
  Zebra/cs.lproj/Localizable.strings
  Zebra/da.lproj/Localizable.strings
  Zebra/de.lproj/Localizable.strings
  Zebra/el.lproj/Localizable.strings
  Zebra/es.lproj/Localizable.strings
  Zebra/fa.lproj/Localizable.strings
  Zebra/fr.lproj/Localizable.strings
  Zebra/he.lproj/Localizable.strings
  Zebra/hi.lproj/Localizable.strings
  Zebra/hr.lproj/Localizable.strings
  Zebra/it.lproj/Localizable.strings
  Zebra/ja.lproj/Localizable.strings
  Zebra/ko.lproj/Localizable.strings
  Zebra/lt.lproj/Localizable.strings
  Zebra/lv.lproj/Localizable.strings
  Zebra/nb.lproj/Localizable.strings
  Zebra/nl.lproj/Localizable.strings
  Zebra/nn.lproj/Localizable.strings
  Zebra/pl.lproj/Localizable.strings
  Zebra/pt-BR.lproj/Localizable.strings
  Zebra/pt.lproj/Localizable.strings
  Zebra/ru.lproj/Localizable.strings
  Zebra/sk.lproj/Localizable.strings
  Zebra/sq.lproj/Localizable.strings
  Zebra/sr.lproj/Localizable.strings
  Zebra/sv.lproj/Localizable.strings
  Zebra/th.lproj/Localizable.strings
  Zebra/tr.lproj/Localizable.strings
  Zebra/vi.lproj/Localizable.strings
  Zebra/zh-Hans.lproj/Localizable.strings
  Zebra/zh-Hant.lproj/Localizable.strings
Labels: localization

#589 [Localization] 1.0~beta28 translations
  Zebra/ar.lproj/Localizable.strings
  Zebra/cs.lproj/Localizable.strings
  Zebra/da.lproj/Localizable.strings
  Zebra/de.lproj/Localizable.strings
  Zebra/el.lproj/Localizable.strings
  Zebra/es.lproj/Localizable.strings
  Zebra/fa.lproj/Localizable.strings
  Zebra/fr.lproj/Localizable.strings
  Zebra/he.lproj/Localizable.strings
  Zebra/hi.lproj/Localizable.strings
  Zebra/hr.lproj/Localizable.strings
  Zebra/it.lproj/Localizable.strings
  Zebra/ja.lproj/Localizable.strings
  Zebra/ko.lproj/Localizable.strings
  Zebra/lt.lproj/Localizable.strings
  Zebra/lv.lproj/Localizable.strings
  Zebra/nb.lproj/Localizable.strings
  Zebra/nl.lproj/Localizable.strings
  Zebra/nn.lproj/Localizable.strings
  Zebra/pl.lproj/Localizable.strings
  Zebra/pt-BR.lproj/Localizable.strings
  Zebra/pt.lproj/Localizable.strings
  Zebra/ru.lproj/Localizable.strings
  Zebra/sk.lproj/Localizable.strings
  Zebra/sq.lproj/Localizable.strings
  Zebra/sr.lproj/Localizable.strings
  Zebra/sv.lproj/Localizable.strings
  Zebra/th.lproj/Localizable.strings
  Zebra/tr.lproj/Localizable.strings
  Zebra/vi.lproj/Localizable.strings
  Zebra/zh-Hans.lproj/Localizable.strings
  Zebra/zh-Hant.lproj/Localizable.strings
Labels: localization, scheduled

#609 [Localization] 1.0~beta29 translations
  Zebra/ar.lproj/Localizable.strings
  Zebra/cs.lproj/Localizable.strings
  Zebra/da.lproj/Localizable.strings
  Zebra/de.lproj/Localizable.strings
  Zebra/el.lproj/Localizable.strings
  Zebra/es.lproj/Localizable.strings
  Zebra/fa.lproj/Localizable.strings
  Zebra/fr.lproj/Localizable.strings
  Zebra/he.lproj/Localizable.strings
  Zebra/hi.lproj/Localizable.strings
  Zebra/hr.lproj/Localizable.strings
  Zebra/it.lproj/Localizable.strings
  Zebra/ja.lproj/Localizable.strings
  Zebra/ko.lproj/Localizable.strings
  Zebra/lt.lproj/Localizable.strings
  Zebra/lv.lproj/Localizable.strings
  Zebra/nb.lproj/Localizable.strings
  Zebra/nl.lproj/Localizable.strings
  Zebra/nn.lproj/Localizable.strings
  Zebra/pl.lproj/Localizable.strings
  Zebra/pt-BR.lproj/Localizable.strings
  Zebra/pt.lproj/Localizable.strings
  Zebra/ru.lproj/Localizable.strings
  Zebra/sk.lproj/Localizable.strings
  Zebra/sq.lproj/Localizable.strings
  Zebra/sr.lproj/Localizable.strings
  Zebra/sv.lproj/Localizable.strings
  Zebra/th.lproj/Localizable.strings
  Zebra/tr.lproj/Localizable.strings
  Zebra/vi.lproj/Localizable.strings
  Zebra/zh-Hans.lproj/Localizable.strings
  Zebra/zh-Hant.lproj/Localizable.strings
Labels: localization, scheduled

#618 Fixed some of the localizations strings.
  Zebra/pl.lproj/Localizable.strings
Labels: localization

#611 [Localization] 1.0~beta30 translations
  Zebra/ar.lproj/Localizable.strings
  Zebra/cs.lproj/Localizable.strings
  Zebra/da.lproj/Localizable.strings
  Zebra/de.lproj/Localizable.strings
  Zebra/el.lproj/Localizable.strings
  Zebra/es.lproj/Localizable.strings
  Zebra/fa.lproj/Localizable.strings
  Zebra/fr.lproj/Localizable.strings
  Zebra/he.lproj/Localizable.strings
  Zebra/hi.lproj/Localizable.strings
  Zebra/hr.lproj/Localizable.strings
  Zebra/it.lproj/Localizable.strings
  Zebra/ja.lproj/Localizable.strings
  Zebra/ko.lproj/Localizable.strings
  Zebra/lt.lproj/Localizable.strings
  Zebra/lv.lproj/Localizable.strings
  Zebra/nb.lproj/Localizable.strings
  Zebra/nl.lproj/Localizable.strings
  Zebra/nn.lproj/Localizable.strings
  Zebra/pl.lproj/Localizable.strings
  Zebra/pt-BR.lproj/Localizable.strings
  Zebra/pt.lproj/Localizable.strings
  Zebra/ru.lproj/Localizable.strings
  Zebra/sk.lproj/Localizable.strings
  Zebra/sq.lproj/Localizable.strings
  Zebra/sr.lproj/Localizable.strings
  Zebra/sv.lproj/Localizable.strings
  Zebra/th.lproj/Localizable.strings
  Zebra/tr.lproj/Localizable.strings
  Zebra/vi.lproj/Localizable.strings
  Zebra/zh-Hans.lproj/Localizable.strings
  Zebra/zh-Hant.lproj/Localizable.strings
Labels: localization, scheduled
